### ISSUE TITLE
severe: installation error Windows.

### ISSUE THREAD

**Issue by NitkarshChourasia** [bra1nDump/ai-task-vscode#3]
Installation error while installing into windows.

```
2023-10-07 13:30:44.796 [warning] Via 'product.json#extensionEnabledApiProposals' extension 'ms-dotnettools.dotnet-interactive-vscode' wants API proposal 'languageConfigurationAutoClosingPairs' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
2023-10-07 13:30:44.810 [warning] Via 'product.json#extensionEnabledApiProposals' extension 'github.copilot-chat' wants API proposal 'terminalContextMenu' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
2023-10-07 13:30:46.747 [error] Extension 'ms-vscode.remote-server' appears in product.json but enables LESS API proposals than the extension wants.
package.json (LOSES): resolvers, tunnelFactory
product.json (WINS): resolvers, tunnels, contribViewsWelcome
2023-10-07 13:30:46.866 [warning] [twxs.cmake]: Cannot register 'cmake.cmakePath'. This property is already registered.
2023-10-07 13:30:47.053 [error] [AnbuselvanRocky.bootstrap5-vscode]: Unknown language in `contributes.bootstrap5-vscode.language`. Provided value: blade
2023-10-07 13:30:47.053 [error] [AnbuselvanRocky.bootstrap5-vscode]: Unknown language in `contributes.bootstrap5-vscode.language`. Provided value: ejs
2023-10-07 13:30:47.053 [error] [AnbuselvanRocky.bootstrap5-vscode]: Unknown language in `contributes.bootstrap5-vscode.language`. Provided value: latte
2023-10-07 13:30:47.053 [error] [AnbuselvanRocky.bootstrap5-vscode]: Unknown language in `contributes.bootstrap5-vscode.language`. Provided value: tpl
2023-10-07 13:30:47.054 [error] [AnbuselvanRocky.bootstrap5-vscode]: Unknown language in `contributes.bootstrap5-vscode.language`. Provided value: twig
2023-10-07 13:30:47.054 [error] [AnbuselvanRocky.bootstrap5-vscode]: Unknown language in `contributes.bootstrap5-vscode.language`. Provided value: vue-html
2023-10-07 13:30:47.054 [error] [AnbuselvanRocky.bootstrap5-vscode]: Unknown language in `contributes.bootstrap5-vscode.language`. Provided value: django-html
2023-10-07 13:30:47.054 [error] [AnbuselvanRocky.bootstrap5-vscode]: Unknown language in `contributes.bootstrap5-vscode.language`. Provided value: jinja-html
2023-10-07 13:30:47.055 [error] [AnbuselvanRocky.bootstrap5-vscode]: Unknown language in `contributes.bootstrap5-vscode.language`. Provided value: erb
2023-10-07 13:30:47.055 [error] [AnbuselvanRocky.bootstrap5-vscode]: Unknown language in `contributes.bootstrap5-vscode.language`. Provided value: HTML (Eex)
2023-10-07 13:30:47.055 [error] [AnbuselvanRocky.bootstrap5-vscode]: Unknown language in `contributes.bootstrap5-vscode.language`. Provided value: volt
2023-10-07 13:30:47.056 [error] [AnbuselvanRocky.bootstrap5-vscode]: Unknown language in `contributes.bootstrap5-vscode.language`. Provided value: nunjucks
2023-10-07 13:30:47.056 [error] [AnbuselvanRocky.bootstrap5-vscode]: Unknown language in `contributes.bootstrap5-vscode.language`. Provided value: sass
2023-10-07 13:30:47.056 [error] [AnbuselvanRocky.bootstrap5-vscode]: Unknown language in `contributes.bootstrap5-vscode.language`. Provided value: svelte
2023-10-07 13:30:50.846 [info] [perf] Render performance baseline is 50ms
2023-10-07 13:30:53.419 [error] [Extension Host] Failed to load message bundle for file c:\Users\playn\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-2.1.3\out\extension
2023-10-07 13:30:53.420 [error] [Extension Host] Failed to load message bundle for file c:\Users\playn\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-2.1.3\out\extension
2023-10-07 13:30:53.423 [error] [Extension Host] Failed to load message bundle for file c:\Users\playn\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-2.1.3\out\extension
2023-10-07 13:30:53.424 [error] [Extension Host] Failed to load message bundle for file c:\Users\playn\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-2.1.3\out\extension
2023-10-07 13:30:53.425 [error] [Extension Host] Failed to load message bundle for file c:\Users\playn\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-2.1.3\out\extension
2023-10-07 13:30:53.425 [error] [Extension Host] Failed to load message bundle for file c:\Users\playn\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-2.1.3\out\extension
2023-10-07 13:30:53.426 [error] [Extension Host] Failed to load message bundle for file c:\Users\playn\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-2.1.3\out\extension
2023-10-07 13:30:53.426 [error] [Extension Host] Failed to load message bundle for file c:\Users\playn\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-2.1.3\out\extension
2023-10-07 13:31:05.525 [error] [Extension Host] (node:17344) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `Code --trace-deprecation ...` to show where the warning was created)
2023-10-07 13:41:23.821 [error] Cannot read properties of undefined (reading 'data'): TypeError: Cannot read properties of undefined (reading 'data')
    at c:\Users\playn\.vscode\extensions\ms-python.vscode-pylance-2023.10.10\dist\extension.bundle.js:1:72139
    at _0x552b27 (c:\Users\playn\.vscode\extensions\ms-python.vscode-pylance-2023.10.10\dist\extension.bundle.js:1:83959)
    at me.provideCompletionItems (c:\Users\playn\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:127:50662)
2023-10-07 13:43:32.680 [error] CorruptZip: end of central directory record signature not found
    at w.download (c:\Users\playn\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:109:141)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async W.x (c:\Users\playn\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:109:19882)
    at async W.h (c:\Users\playn\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:109:17926)
2023-10-07 13:43:32.707 [error] end of central directory record signature not found: CorruptZip: end of central directory record signature not found
    at w.download (c:\Users\playn\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:109:141)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async W.x (c:\Users\playn\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:109:19882)
    at async W.h (c:\Users\playn\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:109:17926)
    
```

**Comment by bra1nDump** [comment]
Thanks for testing this on windows!
Based on the logs it seems the error is coming from a different extension: vscode-pylance-2023

**Comment by NitkarshChourasia** [comment]
So, it is basically reacting with other dependencies.
So, it must be solved, right?

**Comment by NitkarshChourasia** [comment]
So, it is basically reacting with other dependencies.
So, it must be solved, right?
Because, I think it is a bug.

**Comment by bra1nDump** [comment]
Can you try and record the following steps:
1. Install the extension from the extension marketplace 
2. Open a folder with a single typescript file
3. Create a comment like so // @task replace this line with a hello world console log 
4. Hit run button above the @task mention 

Have you watched the demo in the readme?

**Comment by NitkarshChourasia** [comment]
So, it only works for typescript files only.
No python, or java, etc.,.?

**Comment by NitkarshChourasia** [comment]
> Installation error while installing into windows.
> 
> ```
> 2023-10-07 13:30:44.796 [warning] Via 'product.json#extensionEnabledApiProposals' extension 'ms-dotnettools.dotnet-interactive-vscode' wants API proposal 'languageConfigurationAutoClosingPairs' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
> 2023-10-07 13:30:44.810 [warning] Via 'product.json#extensionEnabledApiProposals' extension 'github.copilot-chat' wants API proposal 'terminalContextMenu' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
> 2023-10-07 13:30:46.747 [error] Extension 'ms-vscode.remote-server' appears in product.json but enables LESS API proposals than the extension wants.
> package.json (LOSES): resolvers, tunnelFactory
> product.json (WINS): resolvers, tunnels, contribViewsWelcome
> 2023-10-07 13:30:46.866 [warning] [twxs.cmake]: Cannot register 'cmake.cmakePath'. This property is already registered.
> 2023-10-07 13:30:47.053 [error] [AnbuselvanRocky.bootstrap5-vscode]: Unknown language in `contributes.bootstrap5-vscode.language`. Provided value: blade
> 2023-10-07 13:30:47.053 [error] [AnbuselvanRocky.bootstrap5-vscode]: Unknown language in `contributes.bootstrap5-vscode.language`. Provided value: ejs
> 2023-10-07 13:30:47.053 [error] [AnbuselvanRocky.bootstrap5-vscode]: Unknown language in `contributes.bootstrap5-vscode.language`. Provided value: latte
> 2023-10-07 13:30:47.053 [error] [AnbuselvanRocky.bootstrap5-vscode]: Unknown language in `contributes.bootstrap5-vscode.language`. Provided value: tpl
> 2023-10-07 13:30:47.054 [error] [AnbuselvanRocky.bootstrap5-vscode]: Unknown language in `contributes.bootstrap5-vscode.language`. Provided value: twig
> 2023-10-07 13:30:47.054 [error] [AnbuselvanRocky.bootstrap5-vscode]: Unknown language in `contributes.bootstrap5-vscode.language`. Provided value: vue-html
> 2023-10-07 13:30:47.054 [error] [AnbuselvanRocky.bootstrap5-vscode]: Unknown language in `contributes.bootstrap5-vscode.language`. Provided value: django-html
> 2023-10-07 13:30:47.054 [error] [AnbuselvanRocky.bootstrap5-vscode]: Unknown language in `contributes.bootstrap5-vscode.language`. Provided value: jinja-html
> 2023-10-07 13:30:47.055 [error] [AnbuselvanRocky.bootstrap5-vscode]: Unknown language in `contributes.bootstrap5-vscode.language`. Provided value: erb
> 2023-10-07 13:30:47.055 [error] [AnbuselvanRocky.bootstrap5-vscode]: Unknown language in `contributes.bootstrap5-vscode.language`. Provided value: HTML (Eex)
> 2023-10-07 13:30:47.055 [error] [AnbuselvanRocky.bootstrap5-vscode]: Unknown language in `contributes.bootstrap5-vscode.language`. Provided value: volt
> 2023-10-07 13:30:47.056 [error] [AnbuselvanRocky.bootstrap5-vscode]: Unknown language in `contributes.bootstrap5-vscode.language`. Provided value: nunjucks
> 2023-10-07 13:30:47.056 [error] [AnbuselvanRocky.bootstrap5-vscode]: Unknown language in `contributes.bootstrap5-vscode.language`. Provided value: sass
> 2023-10-07 13:30:47.056 [error] [AnbuselvanRocky.bootstrap5-vscode]: Unknown language in `contributes.bootstrap5-vscode.language`. Provided value: svelte
> 2023-10-07 13:30:50.846 [info] [perf] Render performance baseline is 50ms
> 2023-10-07 13:30:53.419 [error] [Extension Host] Failed to load message bundle for file c:\Users\playn\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-2.1.3\out\extension
> 2023-10-07 13:30:53.420 [error] [Extension Host] Failed to load message bundle for file c:\Users\playn\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-2.1.3\out\extension
> 2023-10-07 13:30:53.423 [error] [Extension Host] Failed to load message bundle for file c:\Users\playn\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-2.1.3\out\extension
> 2023-10-07 13:30:53.424 [error] [Extension Host] Failed to load message bundle for file c:\Users\playn\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-2.1.3\out\extension
> 2023-10-07 13:30:53.425 [error] [Extension Host] Failed to load message bundle for file c:\Users\playn\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-2.1.3\out\extension
> 2023-10-07 13:30:53.425 [error] [Extension Host] Failed to load message bundle for file c:\Users\playn\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-2.1.3\out\extension
> 2023-10-07 13:30:53.426 [error] [Extension Host] Failed to load message bundle for file c:\Users\playn\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-2.1.3\out\extension
> 2023-10-07 13:30:53.426 [error] [Extension Host] Failed to load message bundle for file c:\Users\playn\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-2.1.3\out\extension
> 2023-10-07 13:31:05.525 [error] [Extension Host] (node:17344) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
> (Use `Code --trace-deprecation ...` to show where the warning was created)
> 2023-10-07 13:41:23.821 [error] Cannot read properties of undefined (reading 'data'): TypeError: Cannot read properties of undefined (reading 'data')
>     at c:\Users\playn\.vscode\extensions\ms-python.vscode-pylance-2023.10.10\dist\extension.bundle.js:1:72139
>     at _0x552b27 (c:\Users\playn\.vscode\extensions\ms-python.vscode-pylance-2023.10.10\dist\extension.bundle.js:1:83959)
>     at me.provideCompletionItems (c:\Users\playn\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:127:50662)
> 2023-10-07 13:43:32.680 [error] CorruptZip: end of central directory record signature not found
>     at w.download (c:\Users\playn\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:109:141)
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at async W.x (c:\Users\playn\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:109:19882)
>     at async W.h (c:\Users\playn\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:109:17926)
> 2023-10-07 13:43:32.707 [error] end of central directory record signature not found: CorruptZip: end of central directory record signature not found
>     at w.download (c:\Users\playn\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:109:141)
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at async W.x (c:\Users\playn\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:109:19882)
>     at async W.h (c:\Users\playn\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:109:17926)
>     
> ```

I don't know, but when I installed today from the extensions side - bar today.
It first failed to download.
When I tried again, it was finally **installed** successfully.

**Comment by NitkarshChourasia** [comment]
> Can you try and record the following steps:
> 
> 1. Install the extension from the extension marketplace
> 2. Open a folder with a single typescript file
> 3. Create a comment like so // @task replace this line with a hello world console log
> 4. Hit run button above the @task mention
> 
> Have you watched the demo in the readme?

![image](https://github.com/bra1nDump/ai-task-vscode/assets/90651616/d85b6c1e-e1de-4716-b3c3-fccaaddc3d8c)
It worked successfully.
Now, next?!

**Comment by bra1nDump** [comment]
This looks resolved, continuing conversion on running locally in a different issue #4
